# Python CircleCI 2.0 configuration file
version: 2
orbs:
      codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo  pip install pipenv
            pipenv --three
            pipenv install
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pipenv run pytest -v --cov ./crawto
      - run:
          name: return codecoverage metric
          command: | 
              pipenv run codecov
